/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import java.io.File;
import classes.Employee;
import com.opencsv.exceptions.CsvValidationException;
import java.awt.Dialog;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author ajbab
 */
public class frmUpdateEmployee extends javax.swing.JDialog {

    /**
     * Creates new form frmNewEmployee
     */
    private String empno;
    
    public frmUpdateEmployee(String empno) throws IOException, FileNotFoundException, CsvValidationException, ParseException {
        initComponents();
        setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
       
        Employee emp  = new Employee();
        emp = emp.GetEmployeeRecords(empno);
        
       
     
           tfEId.setText(emp.getEmpId());
           tfELName.setText(emp.getEmpLName());
           tfEFName.setText(emp.getEmpFName());
           tfEBirthDate.setText(new SimpleDateFormat("MMMM dd, yyyy").format(emp.getEmpBirthdate()));
           tfEAddress.setText(emp.getEmpAddress());
           tfEPnumber.setText(emp.getEmpPnumber());
           tfESssNo.setText(emp.getEmpSSSNo());
           tfEPhealthNo.setText(emp.getEmpPhealthNo());
           tfETinNo.setText(emp.getEmpTINNo());
           tfEPagIbigNo.setText(emp.getEmpPagIbigNo());
            tfEStatus.setText(emp.getEmpStatus());
            tfEPosition.setText(emp.getEmpPosition());
            tfESupervisor.setText(emp.getEmpISupervisor());
            tfEBasicSalary.setText(String.valueOf(emp.getEmpBasicSalary()));
            tfERiceSubsidy.setText(String.valueOf(emp.getEmpRiceSubsidy()));
            tfEPhoneAllowance.setText(String.valueOf(emp.getEmpPhoneAllowance()));
            tfEClothingAllowance.setText(String.valueOf(emp.getEmpClothingAllowance()));
            tfEGrossSalary.setText(String.valueOf(emp.getEmpGrossSalary()));
            tfEHourlyRate.setText(String.valueOf(emp.getEmpHourlyRate()));
            
          
           
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblEmployeeAddress = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        tfEId = new javax.swing.JTextField();
        tfELName = new javax.swing.JTextField();
        tfEFName = new javax.swing.JTextField();
        btnUpdateEmployee = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        tfEBirthDate = new javax.swing.JTextField();
        lblEmployeeAddress1 = new javax.swing.JLabel();
        tfEAddress = new javax.swing.JTextField();
        lblEmployeeAddress2 = new javax.swing.JLabel();
        tfEPnumber = new javax.swing.JTextField();
        lblEmployeeAddress3 = new javax.swing.JLabel();
        tfESssNo = new javax.swing.JTextField();
        lblEmployeeAddress4 = new javax.swing.JLabel();
        tfEPagIbigNo = new javax.swing.JTextField();
        tfETinNo = new javax.swing.JTextField();
        tfEPhealthNo = new javax.swing.JTextField();
        lblEmployeeAddress5 = new javax.swing.JLabel();
        lblEmployeeAddress6 = new javax.swing.JLabel();
        lblEmployeeAddress7 = new javax.swing.JLabel();
        lblEmployeeAddress9 = new javax.swing.JLabel();
        tfEHourlyRate = new javax.swing.JTextField();
        tfEGrossSalary = new javax.swing.JTextField();
        lblEmployeeAddress10 = new javax.swing.JLabel();
        lblEmployeeAddress11 = new javax.swing.JLabel();
        tfEClothingAllowance = new javax.swing.JTextField();
        tfEPhoneAllowance = new javax.swing.JTextField();
        lblEmployeeAddress12 = new javax.swing.JLabel();
        tfERiceSubsidy = new javax.swing.JTextField();
        lblEmployeeAddress13 = new javax.swing.JLabel();
        tfEBasicSalary = new javax.swing.JTextField();
        lblEmployeeAddress14 = new javax.swing.JLabel();
        tfESupervisor = new javax.swing.JTextField();
        lblEmployeeAddress15 = new javax.swing.JLabel();
        lblEmployeeName1 = new javax.swing.JLabel();
        tfEPosition = new javax.swing.JTextField();
        tfEStatus = new javax.swing.JTextField();
        lblEmployeeID1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 255), new java.awt.Color(255, 255, 0), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 51, 51)));

        lblEmployeeAddress.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress.setText(" First Name:");

        lblEmployeeName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeName.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeName.setText(" LastName:");

        lblEmployeeID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeID.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeID.setText("Employee ID:");

        tfEId.setBackground(new java.awt.Color(0, 0, 0));
        tfEId.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEId.setForeground(new java.awt.Color(255, 255, 255));
        tfEId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEIdActionPerformed(evt);
            }
        });

        tfELName.setBackground(new java.awt.Color(0, 0, 0));
        tfELName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfELName.setForeground(new java.awt.Color(255, 255, 255));

        tfEFName.setBackground(new java.awt.Color(0, 0, 0));
        tfEFName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEFName.setForeground(new java.awt.Color(255, 255, 255));

        btnUpdateEmployee.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateEmployee.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUpdateEmployee.setForeground(new java.awt.Color(204, 204, 255));
        btnUpdateEmployee.setText("Update");
        btnUpdateEmployee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 0), new java.awt.Color(255, 51, 102), new java.awt.Color(0, 51, 255), new java.awt.Color(255, 0, 255)));
        btnUpdateEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateEmployeeSaveStudent(evt);
            }
        });
        btnUpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmployeeActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(0, 0, 0));
        btnClose.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(204, 204, 255));
        btnClose.setText("Close");
        btnClose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 0), new java.awt.Color(255, 51, 102), new java.awt.Color(0, 51, 255), new java.awt.Color(255, 0, 255)));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseFrameClose(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        tfEBirthDate.setBackground(new java.awt.Color(0, 0, 0));
        tfEBirthDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEBirthDate.setForeground(new java.awt.Color(255, 255, 255));

        lblEmployeeAddress1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress1.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress1.setText("Birth Date:");

        tfEAddress.setBackground(new java.awt.Color(0, 0, 0));
        tfEAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEAddress.setForeground(new java.awt.Color(255, 255, 255));

        lblEmployeeAddress2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress2.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress2.setText(" Address:");

        tfEPnumber.setBackground(new java.awt.Color(0, 0, 0));
        tfEPnumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEPnumber.setForeground(new java.awt.Color(255, 255, 255));

        lblEmployeeAddress3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress3.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress3.setText("Phone Number :");

        tfESssNo.setBackground(new java.awt.Color(0, 0, 0));
        tfESssNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfESssNo.setForeground(new java.awt.Color(255, 255, 255));

        lblEmployeeAddress4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress4.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress4.setText("SSS No. :");

        tfEPagIbigNo.setBackground(new java.awt.Color(0, 0, 0));
        tfEPagIbigNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEPagIbigNo.setForeground(new java.awt.Color(255, 255, 255));

        tfETinNo.setBackground(new java.awt.Color(0, 0, 0));
        tfETinNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfETinNo.setForeground(new java.awt.Color(255, 255, 255));

        tfEPhealthNo.setBackground(new java.awt.Color(0, 0, 0));
        tfEPhealthNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEPhealthNo.setForeground(new java.awt.Color(255, 255, 255));

        lblEmployeeAddress5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress5.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress5.setText("PhilHealth No. :");

        lblEmployeeAddress6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress6.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress6.setText("TIN No. :");

        lblEmployeeAddress7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress7.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress7.setText("PagIbig No.: ");

        lblEmployeeAddress9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress9.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress9.setText("Hourly Rate :");

        tfEHourlyRate.setBackground(new java.awt.Color(0, 0, 0));
        tfEHourlyRate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEHourlyRate.setForeground(new java.awt.Color(255, 255, 255));

        tfEGrossSalary.setBackground(new java.awt.Color(0, 0, 0));
        tfEGrossSalary.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEGrossSalary.setForeground(new java.awt.Color(255, 255, 255));

        lblEmployeeAddress10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress10.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress10.setText("Gross Salary :");

        lblEmployeeAddress11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress11.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress11.setText("Clothing Allowance :");

        tfEClothingAllowance.setBackground(new java.awt.Color(0, 0, 0));
        tfEClothingAllowance.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEClothingAllowance.setForeground(new java.awt.Color(255, 255, 255));

        tfEPhoneAllowance.setBackground(new java.awt.Color(0, 0, 0));
        tfEPhoneAllowance.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEPhoneAllowance.setForeground(new java.awt.Color(255, 255, 255));

        lblEmployeeAddress12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress12.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress12.setText("Phone Allowance :");

        tfERiceSubsidy.setBackground(new java.awt.Color(0, 0, 0));
        tfERiceSubsidy.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfERiceSubsidy.setForeground(new java.awt.Color(255, 255, 255));

        lblEmployeeAddress13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress13.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress13.setText("Rice Subsidy :");

        tfEBasicSalary.setBackground(new java.awt.Color(0, 0, 0));
        tfEBasicSalary.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEBasicSalary.setForeground(new java.awt.Color(255, 255, 255));

        lblEmployeeAddress14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress14.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress14.setText("Basic Salary :");

        tfESupervisor.setBackground(new java.awt.Color(0, 0, 0));
        tfESupervisor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfESupervisor.setForeground(new java.awt.Color(255, 255, 255));

        lblEmployeeAddress15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeAddress15.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeAddress15.setText("Supervisor :");

        lblEmployeeName1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeName1.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeName1.setText("Position : ");

        tfEPosition.setBackground(new java.awt.Color(0, 0, 0));
        tfEPosition.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEPosition.setForeground(new java.awt.Color(255, 255, 255));

        tfEStatus.setBackground(new java.awt.Color(0, 0, 0));
        tfEStatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfEStatus.setForeground(new java.awt.Color(255, 255, 255));
        tfEStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEStatusActionPerformed(evt);
            }
        });

        lblEmployeeID1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmployeeID1.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeID1.setText("Status :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnUpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress1)
                                .addGap(18, 18, 18)
                                .addComponent(tfEBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmployeeID)
                                    .addComponent(lblEmployeeName)
                                    .addComponent(lblEmployeeAddress))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfEId)
                                    .addComponent(tfELName)
                                    .addComponent(tfEFName, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress2)
                                .addGap(18, 18, 18)
                                .addComponent(tfEAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress3)
                                .addGap(18, 18, 18)
                                .addComponent(tfEPnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress4)
                                .addGap(18, 18, 18)
                                .addComponent(tfESssNo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress5)
                                .addGap(18, 18, 18)
                                .addComponent(tfEPhealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress6)
                                .addGap(18, 18, 18)
                                .addComponent(tfETinNo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress7)
                                .addGap(18, 18, 18)
                                .addComponent(tfEPagIbigNo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress14)
                                .addGap(18, 18, 18)
                                .addComponent(tfEBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmployeeID1)
                                    .addComponent(lblEmployeeName1)
                                    .addComponent(lblEmployeeAddress15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfEStatus)
                                    .addComponent(tfEPosition)
                                    .addComponent(tfESupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress13)
                                .addGap(18, 18, 18)
                                .addComponent(tfERiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress12)
                                .addGap(18, 18, 18)
                                .addComponent(tfEPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress11)
                                .addGap(18, 18, 18)
                                .addComponent(tfEClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress10)
                                .addGap(18, 18, 18)
                                .addComponent(tfEGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEmployeeAddress9)
                                .addGap(18, 18, 18)
                                .addComponent(tfEHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeeID)
                            .addComponent(tfEId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeeName)
                            .addComponent(tfELName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEPnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfESssNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEPhealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfETinNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEPagIbigNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress7)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeeID1)
                            .addComponent(tfEStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeeName1)
                            .addComponent(tfEPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfESupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfERiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeAddress9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateEmployee)
                    .addComponent(btnClose))
                .addGap(19, 19, 19))
        );

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Employee");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Default.LAPTOP-JISTTHH9\\Downloads\\update student.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEStatusActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCloseFrameClose(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseFrameClose
       
    }//GEN-LAST:event_btnCloseFrameClose

    private void btnUpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmployeeActionPerformed
        Employee employee = new Employee(); 
        
        employee.setEmpId(tfEId.getText());
        employee.setEmpLName(tfELName.getText());
        employee.setEmpFName(tfEFName.getText());
        try {
            employee.setEmpBirthdate(new SimpleDateFormat("MMMM dd, yyyy").parse(tfEBirthDate.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(frmUpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        employee.setEmpAddress(tfEAddress.getText());
        employee.setEmpPnumber(tfEPnumber.getText());
        employee.setEmpSSSNo(tfESssNo.getText());
        employee.setEmpPhealthNo(tfEPhealthNo.getText());
        employee.setEmpTINNo(tfETinNo.getText());
        employee.setEmpPagIbigNo(tfEPagIbigNo.getText());
        employee.setEmpStatus(tfEStatus.getText());
        employee.setEmpPosition(tfEPosition.getText());
        employee.setEmpISupervisor(tfESupervisor.getText());
        employee.setEmpBasicSalary(Double.parseDouble(tfEBasicSalary.getText()));
        employee.setEmpRiceSubsidy(Double.parseDouble(tfERiceSubsidy.getText()));
        employee.setEmpPhoneAllowance(Double.parseDouble(tfEPhoneAllowance.getText()));
        employee.setEmpClothingAllowance(Double.parseDouble(tfEClothingAllowance.getText()));
        employee.setEmpGrossSalary(Double.parseDouble(tfEGrossSalary.getText()));
        employee.setEmpHourlyRate(Double.parseDouble(tfEHourlyRate.getText()));
     
      
      String CSVFilename = "Employee.csv";
      
        try {
            
            try {
                employee.UpdateEmployee(CSVFilename);
            } catch (IOException ex) {
                Logger.getLogger(frmUpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
          
            tfEId.setText("");
            tfELName.setText("");
            tfEFName.setText("");
            tfEBirthDate.setText("");
            tfEAddress.setText("");
            tfEPnumber.setText("");
            tfESssNo.setText("");
            tfEPhealthNo.setText("");
            tfETinNo.setText("");
            tfEPagIbigNo.setText("");
            tfEStatus.setText("");
            tfEPosition.setText("");
            tfESupervisor.setText("");
            tfEBasicSalary.setText("");
            tfERiceSubsidy.setText("");
            tfEPhoneAllowance.setText("");
            tfEClothingAllowance.setText("");
            tfEGrossSalary.setText("");
            tfEHourlyRate.setText("");

       
        } catch (CsvValidationException ex) {
            Logger.getLogger(frmUpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);

        }
        
    }//GEN-LAST:event_btnUpdateEmployeeActionPerformed

    private void btnUpdateEmployeeSaveStudent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateEmployeeSaveStudent
   
      
/**      String dateString = tfEBirthDate.getText();
SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy"); // adjust the format based on your input
Date birthdate = null;

try {
    birthdate = dateFormat.parse(dateString);
} catch (ParseException e) {
    e.printStackTrace(); // handle the parse exception as needed
}

//parse to double
String salaryText = tfEBasicSalary.getText();
double basicSalary = 0;

try {
    basicSalary = Double.parseDouble(salaryText);
} catch (NumberFormatException e) {
    e.printStackTrace(); // handle the parse exception as needed
    // Optionally, provide a default value or error handling logic
}

String riceSubsidyText = tfERiceSubsidy.getText();
double riceSubsidy = 0;

try {
    riceSubsidy = Double.parseDouble(riceSubsidyText);
} catch (NumberFormatException e) {
    e.printStackTrace(); // handle the parse exception as needed
    // Optionally, provide a default value or error handling logic
}

String phoneAllowanceText = tfEPhoneAllowance.getText();
double phoneAllowance = 0;

try {
    phoneAllowance = Double.parseDouble(phoneAllowanceText);
} catch (NumberFormatException e) {
    e.printStackTrace(); // handle the parse exception as needed
    // Optionally, provide a default value or error handling logic
}

String clothingAllowanceText = tfEClothingAllowance.getText();
double clothingAllowance = 0;

try {
    clothingAllowance = Double.parseDouble(clothingAllowanceText);
} catch (NumberFormatException e) {
    e.printStackTrace(); // handle the parse exception as needed
    // Optionally, provide a default value or error handling logic
}

String grossSalaryText = tfEGrossSalary.getText();
double grossSalary = 0;

try {
    grossSalary = Double.parseDouble(grossSalaryText);
} catch (NumberFormatException e) {
    e.printStackTrace(); // handle the parse exception as needed
    // Optionally, provide a default value or error handling logic
}

String hourlyRateText = tfEHourlyRate.getText();
double hourlyRate = 0;

try {
    hourlyRate = Double.parseDouble(hourlyRateText);
} catch (NumberFormatException e) {
    e.printStackTrace(); // handle the parse exception as needed
    // Optionally, provide a default value or error handling logic
}**/

        
    }//GEN-LAST:event_btnUpdateEmployeeSaveStudent

    private void tfEIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnUpdateEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblEmployeeAddress;
    private javax.swing.JLabel lblEmployeeAddress1;
    private javax.swing.JLabel lblEmployeeAddress10;
    private javax.swing.JLabel lblEmployeeAddress11;
    private javax.swing.JLabel lblEmployeeAddress12;
    private javax.swing.JLabel lblEmployeeAddress13;
    private javax.swing.JLabel lblEmployeeAddress14;
    private javax.swing.JLabel lblEmployeeAddress15;
    private javax.swing.JLabel lblEmployeeAddress2;
    private javax.swing.JLabel lblEmployeeAddress3;
    private javax.swing.JLabel lblEmployeeAddress4;
    private javax.swing.JLabel lblEmployeeAddress5;
    private javax.swing.JLabel lblEmployeeAddress6;
    private javax.swing.JLabel lblEmployeeAddress7;
    private javax.swing.JLabel lblEmployeeAddress9;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeID1;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblEmployeeName1;
    private javax.swing.JTextField tfEAddress;
    private javax.swing.JTextField tfEBasicSalary;
    private javax.swing.JTextField tfEBirthDate;
    private javax.swing.JTextField tfEClothingAllowance;
    private javax.swing.JTextField tfEFName;
    private javax.swing.JTextField tfEGrossSalary;
    private javax.swing.JTextField tfEHourlyRate;
    private javax.swing.JTextField tfEId;
    private javax.swing.JTextField tfELName;
    private javax.swing.JTextField tfEPagIbigNo;
    private javax.swing.JTextField tfEPhealthNo;
    private javax.swing.JTextField tfEPhoneAllowance;
    private javax.swing.JTextField tfEPnumber;
    private javax.swing.JTextField tfEPosition;
    private javax.swing.JTextField tfERiceSubsidy;
    private javax.swing.JTextField tfESssNo;
    private javax.swing.JTextField tfEStatus;
    private javax.swing.JTextField tfESupervisor;
    private javax.swing.JTextField tfETinNo;
    // End of variables declaration//GEN-END:variables
}
